'use client';

import * as React from 'react';
import { useSearchParams } from 'next/navigation';
import { useRouter } from '@myorg/shared/util-i18n';
import { useTranslations } from 'next-intl';
import { ColumnDef } from '@tanstack/react-table';
import { Button, DataTable } from '@myorg/shared/ui';
import { formatDate } from '@myorg/shared/util-dates';

import {
  useJournalDetailQuery,
  type JournalNormalizationRow,
  type JournalRawData,
} from '@myorg/modules/journal-entries-new/data-access';
import { JOURNAL_DATETIME_FORMAT, FIXED_TOKEN_TYPES } from '@myorg/modules/journal-entries-new/util';

const EMPTY_DISPLAY = '--';

type MappingMethod = 1 | 2 | 3;

interface BasicKvRow {
  key: string;
  label: string;
  value: string;
}

/** 详情页 Posting Entry 行（注入 `id` 以满足 DataTable 契约）。 */
interface PostingEntryRow extends JournalNormalizationRow {
  id: string;
}

/** 1:1 迁移自源项目 `parseTdTxId`：将 query 值解析为正整数，非法返回 `undefined`。 */
function parseTdTxId(value: string | null): number | undefined {
  if (!value) return undefined;
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return undefined;
  return parsed;
}

/** 1:1 迁移自源项目 `toTextValue`：空值 → '--'，其余转字符串。 */
function toTextValue(value: unknown): string {
  if (value === null || value === undefined || value === '') return EMPTY_DISPLAY;
  if (typeof value === 'string') return value;
  return String(value);
}

/** 1:1 迁移自源项目 `resolveMappingMethodLabel`。 */
function resolveMappingMethodLabel(mappingMethod?: number): string {
  const map: Record<MappingMethod, string> = {
    1: 'DIRECT',
    2: 'CONSTANT',
    3: 'GENERATE',
  };
  if (mappingMethod === 1 || mappingMethod === 2 || mappingMethod === 3) {
    return map[mappingMethod];
  }
  return EMPTY_DISPLAY;
}

/** 1:1 迁移自源项目 `resolveNormalizationLogicLabel`。 */
function resolveNormalizationLogicLabel(row: JournalNormalizationRow): string {
  const mappingField = row.mappingField || '';
  const normalizedField = mappingField.trim().toUpperCase();

  if (normalizedField === 'DR_ACCT' || normalizedField === 'CR_ACCT') {
    return 'Retrieve from Posting Engine';
  }

  if (row.mappingMethod === 3) {
    return 'Automatically generated by the system';
  }

  if (row.mappingMethod === 2) {
    return row.fieldValue || EMPTY_DISPLAY;
  }

  if (row.mappingMethod === 1) {
    if (mappingField === 'Finality Date') {
      return 'Based on the finality consensus of the specific chain (e.g., 6 blocks for BTC)';
    }
    if (mappingField === 'Value Date') {
      return 'Directly mapped from the on-chain finality date';
    }
    return `Directly mapped from the original ${
      mappingField || row.sourceField || 'field'
    }`;
  }

  return resolveMappingMethodLabel(row.mappingMethod);
}

/** 1:1 迁移自源项目 `formatJsonText`：对象/JSON 字符串美化，异常回退原值。 */
function formatJsonText(value: unknown): string {
  if (value === null || value === undefined || value === '') return EMPTY_DISPLAY;
  try {
    const parsedValue = typeof value === 'string' ? JSON.parse(value) : value;
    return JSON.stringify(parsedValue, null, 2);
  } catch {
    return String(value);
  }
}

/** 1:1 迁移自源项目 `formatTAccountAmount`：去逗号 → 数字 → 2 位 Intl；0/空 → ''。 */
function formatTAccountAmount(value?: string | number): string {
  if (value === null || value === undefined || value === '') return '';
  const amount = Number(String(value).replace(/,/g, ''));
  if (!Number.isFinite(amount)) return String(value);
  if (amount === 0) return '';
  return new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

interface TokenTypeOption {
  value: number;
  label: string;
}

/**
 * 1:1 迁移自源项目 `formatNormalizationValue`。
 * 对 Status / Token Type / Transaction Amount / *Date* 字段做专属格式化，其余 `toTextValue`。
 */
function formatNormalizationValue(
  fieldValue: string | number | undefined,
  mappingField: JournalNormalizationRow['mappingField'],
  tokenTypeOptions: TokenTypeOption[]
): string {
  if (mappingField === 'Status') return 'Success';

  const value = toTextValue(fieldValue);
  if (mappingField === 'Token Type') {
    const tokenType = Number(value);
    const option = tokenTypeOptions.find((item) => item.value === tokenType);
    return option?.label || value;
  }

  if (mappingField === 'Transaction Amount') {
    const amount = Number(value);
    return Number.isFinite(amount) ? amount.toFixed(2) : value;
  }

  if (value === EMPTY_DISPLAY || !mappingField?.includes('Date')) {
    return value;
  }

  const timestamp = Number(value);
  if (!Number.isFinite(timestamp)) return value;
  return formatDate(timestamp, JOURNAL_DATETIME_FORMAT);
}

/**
 * JournalEntriesNewDetailPage — 单笔 journal 详情（4 区块）。
 *
 * 迁移自源项目 `td-manage` 的 `detail.tsx`：
 * 1. Raw Data（左 blockData JSON / 右 rawData 键值表）
 * 2. Normalization Engine（normalizedJson 美化）
 * 3. Posting Entry（normalizationData 表）
 * 4. T-Account（TRAN_ID/Book ID + T 字账户卡片）
 *
 * 读取 `tdTxId` query param，用 `useJournalDetailQuery` 加载。
 */
export function JournalEntriesNewDetailPage() {
  const t = useTranslations('modules.journal-entries-new');
  const router = useRouter();
  const searchParams = useSearchParams();

  const tdTxId = parseTdTxId(searchParams.get('tdTxId'));
  const { data: detailData, isLoading } = useJournalDetailQuery(tdTxId);

  const tokenTypeOptions = React.useMemo<TokenTypeOption[]>(
    () =>
      FIXED_TOKEN_TYPES.map((tokenType) => ({
        value: tokenType,
        label: t(`tokenType.${tokenType}`),
      })),
    [t]
  );

  const rawDataRows = React.useMemo<BasicKvRow[]>(() => {
    const rawData: JournalRawData | undefined = detailData?.rawData;
    if (!rawData) return [];

    const formatTs = (ts?: number) =>
      ts ? formatDate(ts, JOURNAL_DATETIME_FORMAT) : EMPTY_DISPLAY;

    const resolveTxTypeLabel = (txType?: number) => {
      if (txType && txType >= 1 && txType <= 7) {
        return t(`transactionType.${txType}`);
      }
      return EMPTY_DISPLAY;
    };

    return [
      { key: 'tdTxId', label: 'tdTxId', value: toTextValue(rawData.tdTxId) },
      { key: 'fromAddress', label: t('field.from'), value: toTextValue(rawData.fromAddress) },
      { key: 'toAddress', label: t('field.to'), value: toTextValue(rawData.toAddress) },
      { key: 'txHash', label: t('field.transactionHash'), value: toTextValue(rawData.txHash) },
      { key: 'tdCount', label: t('field.transactionAmount'), value: toTextValue(rawData.tdCount) },
      { key: 'txType', label: t('field.transactionType'), value: resolveTxTypeLabel(rawData.txType) },
      { key: 'txTime', label: t('field.transactionTime'), value: formatTs(rawData.txTime) },
      { key: 'blockHeight', label: t('detail.blockHeight'), value: toTextValue(rawData.blockHeight) },
      { key: 'blockHash', label: t('detail.blockHash'), value: toTextValue(rawData.blockHash) },
      { key: 'contractAddress', label: t('field.contractAddress'), value: toTextValue(rawData.contractAddress) },
      { key: 'blockDate', label: t('detail.blockTime'), value: formatTs(rawData.blockDate) },
    ];
  }, [detailData?.rawData, t]);

  const postingEntryRows = React.useMemo<PostingEntryRow[]>(() => {
    const rows = detailData?.normalizationData ?? [];
    return rows.map((row, index) => ({
      ...row,
      id: [row.sourceField, row.mappingField, row.fieldValue, row.mappingMethod, index].join('|'),
    }));
  }, [detailData?.normalizationData]);

  const tAccountRows = React.useMemo(
    () => detailData?.tAccounts || detailData?.taccounts || [],
    [detailData?.tAccounts, detailData?.taccounts]
  );

  const normalizedJsonString = React.useMemo(() => {
    const normalizedJson = detailData?.normalizedJson;
    if (!normalizedJson) return EMPTY_DISPLAY;
    return JSON.stringify(normalizedJson, null, 2);
  }, [detailData?.normalizedJson]);

  const blockDataString = React.useMemo(
    () => formatJsonText(detailData?.rawData?.blockData),
    [detailData?.rawData?.blockData]
  );

  const postingEntryColumns = React.useMemo<ColumnDef<PostingEntryRow>[]>(
    () => [
      {
        accessorKey: 'mappingField',
        header: t('detail.columnName'),
        cell: ({ row }) => (
          <span>{row.original.mappingField || EMPTY_DISPLAY}</span>
        ),
      },
      {
        accessorKey: 'fieldValue',
        header: t('detail.value'),
        cell: ({ row }) => {
          const normalizedValue = row.original.mappingField
            ? (detailData?.normalizedJson?.[row.original.mappingField] as
                | string
                | number
                | undefined)
            : undefined;
          return (
            <span>
              {formatNormalizationValue(
                normalizedValue ?? row.original.fieldValue,
                row.original.mappingField,
                tokenTypeOptions
              )}
            </span>
          );
        },
      },
      {
        id: 'logicType',
        header: t('detail.logicType'),
        cell: ({ row }) => (
          <span>{resolveNormalizationLogicLabel(row.original)}</span>
        ),
      },
    ],
    [detailData?.normalizedJson, tokenTypeOptions, t]
  );

  const onBack = () => router.back();

  if (!tdTxId) {
    return (
      <div className="rounded-lg border bg-card p-6 shadow-sm">
        <p className="text-sm text-muted-foreground">{t('detail.invalidId')}</p>
        <Button variant="outline" className="mt-4" onClick={onBack}>
          {t('action.back')}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Raw Data */}
      <section className="rounded-lg border bg-card shadow-sm">
        <div className="border-b px-6 py-4 text-base font-semibold">
          {t('detail.rawData')}
        </div>
        <div className="p-4 md:p-5">
          <div className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]">
            <div className="min-w-0 rounded-md border bg-muted/30 p-4">
              <div className="max-h-[420px] overflow-auto">
                <pre className="m-0 whitespace-pre-wrap break-words font-mono text-[13px] leading-6 text-muted-foreground">
                  {blockDataString}
                </pre>
              </div>
            </div>
            <div className="min-w-0 overflow-x-auto rounded-md border">
              <table className="w-full table-fixed border-collapse text-sm">
                <tbody>
                  {rawDataRows.length ? (
                    rawDataRows.map((row) => (
                      <tr key={row.key}>
                        <td className="w-[34%] border bg-muted/30 px-4 py-3 font-medium">
                          {row.label}
                        </td>
                        <td className="break-all border px-4 py-3">{row.value}</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={2} className="border px-4 py-8 text-center text-muted-foreground">
                        {t('empty')}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      {/* Normalization Engine */}
      <section className="rounded-lg border bg-card shadow-sm">
        <div className="border-b px-6 py-4 text-base font-semibold">
          {t('detail.normalizationEngine')}
        </div>
        <div className="p-6">
          <div className="max-h-[360px] overflow-auto rounded-md bg-muted/30 p-6 text-[13px] leading-6 text-muted-foreground">
            <pre className="m-0 whitespace-pre-wrap break-all font-mono">
              {normalizedJsonString}
            </pre>
          </div>
        </div>
      </section>

      {/* Posting Entry */}
      <section className="rounded-lg border bg-card shadow-sm">
        <div className="border-b px-6 py-4 text-base font-semibold">
          {t('detail.postingEntry')}
        </div>
        <div className="p-6">
          <DataTable
            columns={postingEntryColumns}
            data={postingEntryRows}
            isLoading={isLoading}
            emptyMessage={t('empty')}
          />
        </div>
      </section>

      {/* T-Account */}
      <section className="rounded-lg border bg-card shadow-sm">
        <div className="border-b px-6 py-4 text-base font-semibold">
          {t('detail.tAccount')}
        </div>
        <div className="p-6">
          <div className="rounded-md bg-muted/30">
            <div className="flex flex-wrap gap-x-16 gap-y-3 border-b bg-background px-4 py-3 text-sm">
              <div>
                <span className="font-semibold">TRAN_ID:</span>{' '}
                {detailData?.tranId || EMPTY_DISPLAY}
              </div>
              <div>
                <span className="font-semibold">{t('detail.bookId')}:</span>{' '}
                {detailData?.bookNo || EMPTY_DISPLAY}
              </div>
            </div>
            {tAccountRows.length ? (
              <div className="flex flex-wrap gap-x-20 gap-y-10 p-6">
                {tAccountRows.map((row, index) => (
                  <div
                    key={`${row.accountCode || 'account'}-${index}`}
                    className="w-[464px] max-w-full text-sm"
                  >
                    <div className="text-center text-base font-semibold">
                      {row.accountCode || EMPTY_DISPLAY}&nbsp;&nbsp;
                      {row.accountName || EMPTY_DISPLAY}
                    </div>
                    <div className="relative mt-6 min-h-[260px]">
                      <div className="absolute left-0 right-0 top-0 border-t-2 border-dashed border-primary/60" />
                      <div className="absolute left-1/2 top-[14px] h-[220px] border-l-2 border-dashed border-primary/60" />
                      <div className="grid grid-cols-2">
                        <div className="px-6 py-7 text-center">
                          <div className="font-semibold">{t('detail.debit')}</div>
                          <div className="mt-8">{formatTAccountAmount(row.debitAmount)}</div>
                        </div>
                        <div className="px-6 py-7 text-center">
                          <div className="font-semibold">{t('detail.credit')}</div>
                          <div className="mt-8">{formatTAccountAmount(row.creditAmount)}</div>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="px-6 py-10 text-center text-muted-foreground">
                {t('empty')}
              </div>
            )}
          </div>
        </div>
      </section>

      <div className="flex justify-end">
        <Button variant="outline" onClick={onBack}>
          {t('action.back')}
        </Button>
      </div>
    </div>
  );
}
